# Generated by Django 4.2.6 on 2023-10-29 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Пол')),
            ],
        ),
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('description', models.TextField(blank=True, verbose_name='История')),
                ('birth_date', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('death_date', models.DateField(blank=True, verbose_name='Дата смерти')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обнавления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('category', models.ManyToManyField(to='muslim_heroes.category', verbose_name='Категория')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='muslim_heroes.gender', verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Герой Ислама',
                'verbose_name_plural': 'Герои Ислама',
            },
        ),
    ]
